version: "3.7"

services:
  db:
    image: mysql:5.7.27
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    ports:
      - 4000:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
    - laravel

  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
    ports:
      - 8001:80
    networks:
    - laravel
    
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
    - laravel

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

networks:
  laravel:
    driver: bridge